import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';

export interface Invoice {
  id: string;
  user_id: string;
  client_id: string;
  contract_id: string | null;
  invoice_number: string;
  subtotal: number;
  tax_amount: number;
  total: number;
  issue_date: string;
  due_date: string;
  status: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
  notes: string | null;
  sent_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface InvoiceItem {
  id: string;
  invoice_id: string;
  description: string;
  quantity: number;
  unit_price: number;
  amount: number;
  created_at: string;
}

export interface InvoiceFormData {
  id?: string;
  clientId: string;
  contractId?: string;
  items: {
    description: string;
    quantity: number;
    unitPrice: number;
  }[];
  taxRate: number;
  dueDate: string;
  notes: string;
}

export const useInvoices = () => {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  const invoicesQuery = useQuery({
    queryKey: ['invoices', user?.id],
    queryFn: async () => {
      if (!user) return [];
      const { data, error } = await supabase
        .from('invoices')
        .select('*')
        .order('created_at', { ascending: false });
      
      if (error) throw error;
      return data as Invoice[];
    },
    enabled: !!user,
  });

  const createInvoice = useMutation({
    mutationFn: async (invoiceData: InvoiceFormData) => {
      if (!user) throw new Error('User not authenticated');
      
      const subtotal = invoiceData.items.reduce((sum, item) => sum + (item.quantity * item.unitPrice), 0);
      const taxAmount = subtotal * (invoiceData.taxRate / 100);
      const total = subtotal + taxAmount;
      
      // Create invoice
      const { data: invoice, error: invoiceError } = await supabase
        .from('invoices')
        .insert({
          user_id: user.id,
          client_id: invoiceData.clientId,
          contract_id: invoiceData.contractId || null,
          invoice_number: '', // Will be auto-generated by trigger
          subtotal,
          tax_amount: taxAmount,
          total,
          due_date: invoiceData.dueDate,
          notes: invoiceData.notes || null,
          status: 'draft' as const,
        })
        .select()
        .single();
      
      if (invoiceError) throw invoiceError;
      
      // Create invoice items
      const items = invoiceData.items.map(item => ({
        invoice_id: invoice.id,
        description: item.description,
        quantity: item.quantity,
        unit_price: item.unitPrice,
        amount: item.quantity * item.unitPrice,
      }));
      
      const { error: itemsError } = await supabase
        .from('invoice_items')
        .insert(items);
      
      if (itemsError) throw itemsError;
      
      return invoice;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['invoices'] });
      toast.success('Invoice created successfully');
    },
    onError: (error: Error) => {
      toast.error(`Failed to create invoice: ${error.message}`);
    },
  });

  const createInvoiceFromContract = useMutation({
    mutationFn: async (contractId: string) => {
      if (!user) throw new Error('User not authenticated');
      
      // Get the contract
      const { data: contract, error: contractError } = await supabase
        .from('contracts')
        .select('*')
        .eq('id', contractId)
        .single();
      
      if (contractError) throw contractError;
      
      const subtotal = contract.amount;
      const taxRate = 10; // Default tax rate
      const taxAmount = subtotal * (taxRate / 100);
      const total = subtotal + taxAmount;
      
      // Set due date to 30 days from now
      const dueDate = new Date();
      dueDate.setDate(dueDate.getDate() + 30);
      
      // Create invoice
      const { data: invoice, error: invoiceError } = await supabase
        .from('invoices')
        .insert({
          user_id: user.id,
          client_id: contract.client_id,
          contract_id: contractId,
          invoice_number: '',
          subtotal,
          tax_amount: taxAmount,
          total,
          due_date: dueDate.toISOString().split('T')[0],
          status: 'draft' as const,
        })
        .select()
        .single();
      
      if (invoiceError) throw invoiceError;
      
      // Create invoice item
      const { error: itemError } = await supabase
        .from('invoice_items')
        .insert({
          invoice_id: invoice.id,
          description: contract.title,
          quantity: 1,
          unit_price: subtotal,
          amount: subtotal,
        });
      
      if (itemError) throw itemError;
      
      return invoice;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['invoices'] });
      toast.success('Invoice created from contract');
    },
    onError: (error: Error) => {
      toast.error(`Failed to create invoice: ${error.message}`);
    },
  });

  const sendInvoice = useMutation({
    mutationFn: async (invoiceId: string) => {
      const { data, error } = await supabase
        .from('invoices')
        .update({
          status: 'sent' as const,
          sent_at: new Date().toISOString(),
        })
        .eq('id', invoiceId)
        .select()
        .single();
      
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['invoices'] });
      toast.success('Invoice sent to client');
    },
    onError: (error: Error) => {
      toast.error(`Failed to send invoice: ${error.message}`);
    },
  });

  const updateInvoiceStatus = useMutation({
    mutationFn: async ({ invoiceId, status }: { invoiceId: string; status: Invoice['status'] }) => {
      const { data, error } = await supabase
        .from('invoices')
        .update({ status })
        .eq('id', invoiceId)
        .select()
        .single();
      
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['invoices'] });
    },
    onError: (error: Error) => {
      toast.error(`Failed to update invoice: ${error.message}`);
    },
  });

  return {
    invoices: invoicesQuery.data || [],
    isLoading: invoicesQuery.isLoading,
    error: invoicesQuery.error,
    createInvoice,
    createInvoiceFromContract,
    sendInvoice,
    updateInvoiceStatus,
  };
};
